import { Face, FACE, FaceDataType } from "../types/face";

export const FACES: Record<Face, FaceDataType> = {
    [FACE.AGILITY]: {
        id: FACE.AGILITY,
        description: "Восстановить 10 единиц ловкости",
        target: 0,
        sword: 0,
        agility: 10,
        rage: 0,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.LIGHT_MANA]: {
        id: FACE.LIGHT_MANA,
        description: "Восстановить 10 единиц маны света",
        target: 0,
        sword: 0,
        agility: 0,
        rage: 0,
        light_mana: 10,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.RAGE]: {
        id: FACE.RAGE,
        description: "Восстановить 10 единиц ярости",
        target: 0,
        sword: 0,
        agility: 0,
        rage: 10,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.DARK_MANA]: {
        id: FACE.DARK_MANA,
        description: "Восстановить 10 маны тьмы",
        target: 0,
        sword: 0,
        agility: 0,
        rage: 0,
        light_mana: 0,
        dark_mana: 10,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.DESTRUCTION_MANA]: {
        id: FACE.DESTRUCTION_MANA,
        description: "Восстановить 10 маны разрушения",
        target: 0,
        sword: 0,
        agility: 0,
        rage: 0,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 10,
        heal: 0
    },
    [FACE.SWORD]: {
        id: FACE.SWORD,
        description: "Нанести 10 единиц ближнего урона вражескому артефакту",
        target: 0,
        sword: 10,
        agility: 0,
        rage: 0,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.TARGET]: {
        id: FACE.TARGET,
        description: "Нанести 10 единиц дальнего урона вражескому артефакту",
        target: 10,
        sword: 0,
        agility: 0,
        rage: 0,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.HEAL]: {
        id: FACE.HEAL,
        description: "Восстановить 10 единиц прочности союзному артефакту",
        target: 0,
        sword: 0,
        agility: 0,
        rage: 0,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 10
    },
    [FACE.THREE_SWORD]: {
        id: FACE.THREE_SWORD,
        description: "Нанести 30 единиц ближнего урона вражескому артефакту",
        target: 0,
        sword: 30,
        agility: 0,
        rage: 0,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.TWO_SWORD]: {
        id: FACE.TWO_SWORD,
        description: "Нанести 20 единиц ближнего урона вражескому артефакту",
        target: 0,
        sword: 20,
        agility: 0,
        rage: 0,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.THREE_DARK_MANA]: {
        id: FACE.THREE_DARK_MANA,
        description: "Восстановить 30 единиц маны тьмы",
        target: 0,
        sword: 0,
        agility: 0,
        rage: 0,
        light_mana: 0,
        dark_mana: 30,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.THREE_LIGHT_MANA]: {
        id: FACE.THREE_LIGHT_MANA,
        description: "Восстановить 30 единиц маны света",
        target: 0,
        sword: 0,
        agility: 0,
        rage: 0,
        light_mana: 30,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.THREE_DESTRUCTION_MANA]: {
        id: FACE.THREE_DESTRUCTION_MANA,
        description: "Восстановить 30 единиц маны разрушения",
        target: 0,
        sword: 0,
        agility: 0,
        rage: 0,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 30,
        heal: 0
    },
    [FACE.ONE_EVERY_MANA]: {
        id: FACE.ONE_EVERY_MANA,
        description: "Восстановить 10 единиц маны каждой школы",
        target: 0,
        sword: 0,
        agility: 0,
        rage: 0,
        light_mana: 10,
        dark_mana: 10,
        destruction_mana: 10,
        heal: 0
    },
    [FACE.ONE_RAGE_TWO_TARGET]: {
        id: FACE.ONE_RAGE_TWO_TARGET,
        description: "Восстановить 10 единиц ярости и нанести 20 единиц дальнего урона вражескому артефакту",
        target: 20,
        sword: 0,
        agility: 0,
        rage: 10,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.TWO_RAGE_ONE_TARGET]: {
        id: FACE.TWO_RAGE_ONE_TARGET,
        description: "Восстановить 20 единиц ярости и нанести 10 единиц дальнего урона вражескому артефакту",
        target: 10,
        sword: 0,
        agility: 0,
        rage: 20,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.THREE_HEART]: {
        id: FACE.THREE_HEART,
        description: "Восстановить 30 единиц прочности союзному артефакту",
        target: 0,
        sword: 0,
        agility: 0,
        rage: 0,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 30
    },
    [FACE.ONE_RAGE_TWO_HEART]: {
        id: FACE.ONE_RAGE_TWO_HEART,
        description: "Восстановить 10 единиц ярости и восстановить 20 единиц прочности союзному артефакту",
        target: 0,
        sword: 0,
        agility: 0,
        rage: 10,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 20
    },
    [FACE.THREE_AGILITY]: {
        id: FACE.THREE_AGILITY,
        description: "Восстановить 30 единиц ловкости",
        target: 0,
        sword: 0,
        agility: 30,
        rage: 0,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.THREE_RAGE]: {
        id: FACE.THREE_RAGE,
        description: "Восстановить 30 единиц ярости",
        target: 0,
        sword: 0,
        agility: 0,
        rage: 30,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.TWO_HEART]: {
        id: FACE.TWO_HEART,
        description: "Восстановить 20 единиц прочности союзному артефакту",
        target: 0,
        sword: 0,
        agility: 0,
        rage: 0,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 20
    },
    [FACE.TWO_LIGHT_MANA]: {
        id: FACE.TWO_LIGHT_MANA,
        description: "Восстановить 20 единиц маны света",
        target: 0,
        sword: 0,
        agility: 0,
        rage: 0,
        light_mana: 20,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.TWO_DESTRUCTION_MANA]: {
        id: FACE.TWO_DESTRUCTION_MANA,
        description: "Восстановить 20 единиц маны разрушения",
        target: 0,
        sword: 0,
        agility: 0,
        rage: 0,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 20,
        heal: 0
    },
    [FACE.TWO_DARK_MANA]: {
        id: FACE.TWO_DARK_MANA,
        description: "Восстановить 20 единиц маны тьмы",
        target: 0,
        sword: 0,
        agility: 0,
        rage: 0,
        light_mana: 0,
        dark_mana: 20,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.TWO_RAGE]: {
        id: FACE.TWO_RAGE,
        description: "Восстановить 20 единиц ярости",
        target: 0,
        sword: 0,
        agility: 0,
        rage: 20,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.TWO_DARK_MANA_ONE_RAGE]: {
        id: FACE.TWO_DARK_MANA_ONE_RAGE,
        description: "Восстановить 10 единиц ярости и 20 единиц маны тьмы",
        target: 0,
        sword: 0,
        agility: 0,
        rage: 10,
        light_mana: 0,
        dark_mana: 20,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.ONE_RAGE_ONE_TARGET]: {
        id: FACE.TWO_DARK_MANA_ONE_RAGE,
        description: "Восстановить 10 единиц ярости и нанести 10 единиц дальнего урона вражескому артефакту",
        target: 10,
        sword: 0,
        agility: 0,
        rage: 10,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.ONE_SWORD_ONE_DARK_MANA]: {
        id: FACE.TWO_DARK_MANA_ONE_RAGE,
        description: "Восстановить 10 единиц маны тьмы и нанести 10 единиц ближнего урона вражескому артефакту",
        target: 0,
        sword: 10,
        agility: 0,
        rage: 0,
        light_mana: 0,
        dark_mana: 10,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.ONE_SWORD_ONE_DESTRUCTION_MANA]: {
        id: FACE.ONE_SWORD_ONE_DESTRUCTION_MANA,
        description: "Восстановить 10 единиц маны разрушения и нанести 10 единиц ближнего урона вражескому артефакту",
        target: 0,
        sword: 10,
        agility: 0,
        rage: 0,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 10,
        heal: 0
    },
    [FACE.ONE_SWORD_ONE_RAGE]: {
        id: FACE.ONE_SWORD_ONE_RAGE,
        description: "Восстановить 10 единиц ярости и нанести 10 единиц ближнего урона вражескому артефакту",
        target: 0,
        sword: 10,
        agility: 0,
        rage: 10,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.ONE_SWORD_ONE_AGILITY]: {
        id: FACE.ONE_SWORD_ONE_AGILITY,
        description: "Восстановить 10 единиц ловкости и нанести 10 единиц ближнего урона вражескому артефакту",
        target: 0,
        sword: 10,
        agility: 10,
        rage: 0,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.ONE_SWORD_ONE_LIGHT_MANA]: {
        id: FACE.ONE_SWORD_ONE_LIGHT_MANA,
        description: "Восстановить 10 единиц маны света и нанести 10 единиц ближнего урона вражескому артефакту",
        target: 0,
        sword: 10,
        agility: 0,
        rage: 0,
        light_mana: 10,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.ONE_TARGET_ONE_DESTRUCTION_MANA]: {
        id: FACE.ONE_TARGET_ONE_DESTRUCTION_MANA,
        description: "Восстановить 10 единиц маны разрушения и нанести 10 единиц дальнего урона вражескому артефакту",
        target: 10,
        sword: 0,
        agility: 0,
        rage: 0,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 10,
        heal: 0
    },
    [FACE.ONE_TARGET_ONE_AGILITY]: {
        id: FACE.ONE_TARGET_ONE_AGILITY,
        description: "Восстановить 10 единиц ловкости и нанести 10 единиц дальнего урона вражескому артефакту",
        target: 10,
        sword: 0,
        agility: 10,
        rage: 0,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.TWO_LIGHT_MANA_ONE_TARGET]: {
        id: FACE.ONE_TARGET_ONE_AGILITY,
        description: "Восстановить 20 единиц маны света и нанести 10 единиц дальнего урона вражескому артефакту",
        target: 10,
        sword: 0,
        agility: 0,
        rage: 0,
        light_mana: 20,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.TWO_TARGET_ONE_LIGHT_MANA]: {
        id: FACE.ONE_TARGET_ONE_AGILITY,
        description: "Восстановить 10 единиц маны света и нанести 20 единиц дальнего урона вражескому артефакту",
        target: 20,
        sword: 0,
        agility: 0,
        rage: 0,
        light_mana: 10,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.FOUR_TARGET]: {
        id: FACE.FOUR_TARGET,
        description: "Нанести 40 единиц дальнего урона вражескому артефакту",
        target: 40,
        sword: 0,
        agility: 0,
        rage: 0,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.TWO_AGILITY]: {
        id: FACE.TWO_AGILITY,
        description: "Восстановить 20 единиц ловкости",
        target: 0,
        sword: 0,
        agility: 20,
        rage: 0,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.TWO_RAGE_ONE_LIGHT_MANA]: {
        id: FACE.TWO_RAGE_ONE_LIGHT_MANA,
        description: "Восстановить 20 единиц ярости и 10 единиц маны света",
        target: 0,
        sword: 0,
        agility: 0,
        rage: 20,
        light_mana: 10,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.TWO_TARGET]: {
        id: FACE.TWO_TARGET,
        description: "Нанести 20 единиц дальнего урона вражескому артефакту",
        target: 20,
        sword: 0,
        agility: 0,
        rage: 0,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
    [FACE.THREE_TARGET]: {
        id: FACE.THREE_TARGET,
        description: "Нанести 30 единиц дальнего урона вражескому артефакту",
        target: 30,
        sword: 0,
        agility: 0,
        rage: 0,
        light_mana: 0,
        dark_mana: 0,
        destruction_mana: 0,
        heal: 0
    },
};

