import { ARTIFACT, Artifact } from 'src/artifact/types/artifact';

export const ROBOT_DECK: Artifact[] = [
    ARTIFACT.MOON_STAFF,
    ARTIFACT.BONELORD,
    ARTIFACT.AXE_OF_THE_BERSERKER,
    ARTIFACT.HUNTMASTER,
    ARTIFACT.GRAPPLER,
    ARTIFACT.ILLUSION_BLADE,
    ARTIFACT.ARCANE_SHIELD,
    ARTIFACT.PURIFIER,
    ARTIFACT.VEILSTRIKE,
    ARTIFACT.PALADINS_GLOVE,
    ARTIFACT.AVERTER,
    ARTIFACT.VOLT,
    ARTIFACT.VOIDER,
    ARTIFACT.GLIMPSE,
];
