import { Artifact, ARTIFACT } from "src/artifact/types/artifact";

export const DEFAULT_DECK1: Artifact[] = [
    ARTIFACT.ARCANE_SHIELD,
    ARTIFACT.RING_OF_LIGHT,
    ARTIFACT.RING_OF_DESTRUCTION,
    ARTIFACT.CHRONOS,
    ARTIFACT.MOON_STAFF,
    ARTIFACT.BONELORD,
    ARTIFACT.TEMPER_CROWN,
    ARTIFACT.AXE_OF_THE_BERSERKER,
    ARTIFACT.ILLUSION_BLADE,
    ARTIFACT.GLIMPSE,
    ARTIFACT.HUNTMASTER,
    ARTIFACT.PURIFIER,
    ARTIFACT.VEILSTRIKE,
    ARTIFACT.PALADINS_GLOVE
]

export const DEFAULT_DECK2: Artifact[] = [
    ARTIFACT.AXE_OF_THE_BERSERKER,
    ARTIFACT.ILLUSION_BLADE,
    ARTIFACT.GLIMPSE,
    ARTIFACT.HUNTMASTER,
    ARTIFACT.PURIFIER,
    ARTIFACT.VEILSTRIKE,
    ARTIFACT.PALADINS_GLOVE,
    ARTIFACT.AVERTER,
    ARTIFACT.GRAPPLER,
    ARTIFACT.VOIDER,
    ARTIFACT.CONCEALER,
    ARTIFACT.PLUNDER,
    ARTIFACT.SWIFT_BOOTS,
    ARTIFACT.DIVINE_STAFF,
]

export const DEFAULT_DECK3: Artifact[] = [
    ARTIFACT.MOON_STAFF,
    ARTIFACT.BONELORD,
    ARTIFACT.TEMPER_CROWN,
    ARTIFACT.AXE_OF_THE_BERSERKER,
    ARTIFACT.ILLUSION_BLADE,
    ARTIFACT.GLIMPSE,
    ARTIFACT.HUNTMASTER,
    ARTIFACT.PURIFIER,
    ARTIFACT.VEILSTRIKE,
    ARTIFACT.PALADINS_GLOVE,
    ARTIFACT.AVERTER,
    ARTIFACT.GRAPPLER,
    ARTIFACT.VOIDER,
    ARTIFACT.CONCEALER,
]